### ISSUE TITLE
Java content

### ISSUE THREAD

**Issue by SapitoSucio** [2wayne/EclipsePortable#1]
How can I add Java compatibility ? I mean, I don't see the usual create class and packages buttons

**Comment by 2wayne** [comment]
Quick Guide:
Goto Help > Install New Software... > paste http://download.eclipse.org/mpc/mars/ into "Work with" click "Add.." and type a name e.g. "mpc" wait until the list appears. Select "Select All" and click next etc. until install is finished. Then you find the Eclipse Marketplace under Help. Now you can search e.g. for Java and install a package you like.
