### ISSUE TITLE
System environment

### ISSUE THREAD

**Issue by olegazyx** [2wayne/EclipsePortable#2]
Launcher from ver 4.7.1 return its own environment variable PATH. Launcher from ver 4.6 work fine.

**Comment by 2wayne** [comment]
Sry I don't see your point. Can you elaborate your issue a bit more?

**Comment by olegazyx** [comment]
If use the latest EclipsePortable.exe file, system environment variable PATH looks like on the first screenshot
![short](https://user-images.githubusercontent.com/8065693/33978802-7f1cd83c-e0b2-11e7-83e2-382e7e1c4e2f.png)
If use EclipsePortable.exe file from 4.6 ver
![full](https://user-images.githubusercontent.com/8065693/33978818-92ee65f6-e0b2-11e7-8fb0-14921e8f60ea.png)
